import { defineStore } from 'pinia'

const tournaments = [
    {
        category: 'F',
        teams: [ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H' ],
        players: { min: 4, max: 7 },
        fields: [
            { name: '1', format: '4 v 4', players: 4, duration: 720 },
            { name: '2', format: '3 v 3', players: 3, duration: 720 },
            { name: '3', format: '4 v 4', players: 4, duration: 720 },
            { name: '4', format: '3 v 3', players: 3, duration: 720 },
        ],
        matches: [
            { slot: 0, teams: ['A', 'B'], field: 0 },
            { slot: 0, teams: ['C', 'D'], field: 1 },
            { slot: 0, teams: ['G', 'H'], field: 2 },
            { slot: 0, teams: ['E', 'F'], field: 3 },
            { slot: 1, teams: ['C', 'F'], field: 0 },
            { slot: 1, teams: ['A', 'H'], field: 1 },
            { slot: 1, teams: ['D', 'E'], field: 2 },
            { slot: 1, teams: ['B', 'G'], field: 3 },
            { slot: 2, teams: ['F', 'H'], field: 0 },
            { slot: 2, teams: ['B', 'D'], field: 1 },
            { slot: 2, teams: ['E', 'G'], field: 2 },
            { slot: 2, teams: ['A', 'C'], field: 3 },
            { slot: 3, teams: ['A', 'D'], field: 0 },
            { slot: 3, teams: ['F', 'G'], field: 1 },
            { slot: 3, teams: ['B', 'C'], field: 2 },
            { slot: 3, teams: ['E', 'H'], field: 3 },
            { slot: 4, teams: ['B', 'E'], field: 0 },
            { slot: 4, teams: ['C', 'H'], field: 1 },
            { slot: 4, teams: ['F', 'A'], field: 2 },
            { slot: 4, teams: ['D', 'G'], field: 3 },
            { slot: 5, teams: ['G', 'C'], field: 0 },
            { slot: 5, teams: ['A', 'E'], field: 1 },
            { slot: 5, teams: ['H', 'D'], field: 2 },
            { slot: 5, teams: ['B', 'F'], field: 3 },
            { slot: 6, teams: ['A', 'G'], field: 0 },
            { slot: 6, teams: ['C', 'E'], field: 1 },
            { slot: 6, teams: ['B', 'H'], field: 2 },
            { slot: 6, teams: ['F', 'D'], field: 3 }
        ]
    },
    {
        category: 'F',
        teams: [ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I' ],
        players: { min: 4, max: 7 },
        fields: [
            { name: '1', format: '4 v 4', players: 4, duration: 720 },
            { name: '2', format: '3 v 3', players: 3, duration: 720 },
            { name: '3', format: '4 v 4', players: 4, duration: 720 },
            { name: '4', format: '3 v 3', players: 3, duration: 720 },
            { name: '5', format: '3 v 3', players: 3, duration: 720 }
        ],
        matches: [
            { slot: 0, teams: ['H', 'B'], field: 0 },
            { slot: 0, teams: ['F', 'D'], field: 1 },
            { slot: 0, teams: ['G', 'C'], field: 2 },
            { slot: 0, teams: ['A', 'E'], field: 3 },
            { slot: 0, teams: ['I'], field: 4 },
            { slot: 1, teams: ['A', 'D'], field: 0 },
            { slot: 1, teams: ['B', 'I'], field: 1 },
            { slot: 1, teams: ['H', 'E'], field: 2 },
            { slot: 1, teams: ['F', 'C'], field: 3 },
            { slot: 1, teams: ['G'], field: 4 },
            { slot: 2, teams: ['B', 'C'], field: 0 },
            { slot: 2, teams: ['G', 'A'], field: 1 },
            { slot: 2, teams: ['I', 'F'], field: 2 },
            { slot: 2, teams: ['H', 'D'], field: 3 },
            { slot: 2, teams: ['E'], field: 4 },
            { slot: 3, teams: ['D', 'G'], field: 0 },
            { slot: 3, teams: ['E', 'I'], field: 1 },
            { slot: 3, teams: ['A', 'F'], field: 2 },
            { slot: 3, teams: ['C', 'H'], field: 3 },
            { slot: 3, teams: ['B'], field: 4 },
            { slot: 4, teams: ['I', 'A'], field: 0 },
            { slot: 4, teams: ['B', 'G'], field: 1 },
            { slot: 4, teams: ['H', 'F'], field: 2 },
            { slot: 4, teams: ['E', 'D'], field: 3 },
            { slot: 4, teams: ['C'], field: 4 },
            { slot: 5, teams: ['B', 'E'], field: 0 },
            { slot: 5, teams: ['A', 'H'], field: 1 },
            { slot: 5, teams: ['C', 'D'], field: 2 },
            { slot: 5, teams: ['G', 'I'], field: 3 },
            { slot: 5, teams: ['F'], field: 4 },
            { slot: 6, teams: ['E', 'I'], field: 0 },
            { slot: 6, teams: ['C', 'A'], field: 1 },
            { slot: 6, teams: ['C', 'D'], field: 2 },
            { slot: 6, teams: ['G', 'I'], field: 3 },
            { slot: 6, teams: ['D'], field: 4 }
        ]
    },
    {
        category: 'F',
        teams: [ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J' ],
        players: { min: 4, max: 7 },
        fields: [
            { name: '1', format: '4 v 4', players: 4, duration: 720 },
            { name: '2', format: '3 v 3', players: 3, duration: 720 },
            { name: '3', format: '4 v 4', players: 4, duration: 720 },
            { name: '4', format: '3 v 3', players: 3, duration: 720 },
            { name: '5', format: '4 v 4', players: 4, duration: 720 }
        ],
        matches: [
            { slot: 0, teams: ['J', 'H'], field: 0 },
            { slot: 0, teams: ['B', 'G'], field: 1 },
            { slot: 0, teams: ['A', 'I'], field: 2 },
            { slot: 0, teams: ['F', 'C'], field: 3 },
            { slot: 0, teams: ['D', 'E'], field: 4 },
            { slot: 1, teams: ['B', 'I'], field: 0 },
            { slot: 1, teams: ['E', 'F'], field: 1 },
            { slot: 1, teams: ['D', 'G'], field: 2 },
            { slot: 1, teams: ['C', 'H'], field: 3 },
            { slot: 1, teams: ['A', 'J'], field: 4 },
            { slot: 2, teams: ['C', 'D'], field: 0 },
            { slot: 2, teams: ['A', 'H'], field: 1 },
            { slot: 2, teams: ['J', 'F'], field: 2 },
            { slot: 2, teams: ['G', 'I'], field: 3 },
            { slot: 2, teams: ['B', 'E'], field: 4 },
            { slot: 3, teams: ['A', 'E'], field: 0 },
            { slot: 3, teams: ['I', 'J'], field: 1 },
            { slot: 3, teams: ['H', 'B'], field: 2 },
            { slot: 3, teams: ['F', 'D'], field: 3 },
            { slot: 3, teams: ['G', 'C'], field: 4 },
            { slot: 4, teams: ['I', 'C'], field: 0 },
            { slot: 4, teams: ['G', 'E'], field: 1 },
            { slot: 4, teams: ['H', 'D'], field: 2 },
            { slot: 4, teams: ['J', 'B'], field: 3 },
            { slot: 4, teams: ['A', 'F'], field: 4 },
            { slot: 5, teams: ['E', 'H'], field: 0 },
            { slot: 5, teams: ['D', 'I'], field: 1 },
            { slot: 5, teams: ['C', 'J'], field: 2 },
            { slot: 5, teams: ['B', 'A'], field: 3 },
            { slot: 5, teams: ['G', 'F'], field: 4 },
            { slot: 6, teams: ['B', 'F'], field: 0 },
            { slot: 6, teams: ['J', 'D'], field: 1 },
            { slot: 6, teams: ['I', 'H'], field: 2 },
            { slot: 6, teams: ['A', 'C'], field: 3 },
            { slot: 6, teams: ['G', 'E'], field: 4 }
        ]
    },
    {
        category: 'F',
        teams: [ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K' ],
        players: { min: 4, max: 7 },
        fields: [
            { name: '1', format: '4 v 4', players: 4, duration: 720 },
            { name: '2', format: '3 v 3', players: 3, duration: 720 },
            { name: '3', format: '4 v 4', players: 4, duration: 720 },
            { name: '4', format: '3 v 3', players: 3, duration: 720 },
            { name: '5', format: '4 v 4', players: 4, duration: 720 },
            { name: '6', format: '3 v 3', players: 4, duration: 720 }
        ],
        matches: [
            { slot: 0, teams: ['F', 'H'], field: 0 },
            { slot: 0, teams: ['E', 'C'], field: 1 },
            { slot: 0, teams: ['A', 'I'], field: 2 },
            { slot: 0, teams: ['B', 'J'], field: 3 },
            { slot: 0, teams: ['G', 'K'], field: 4 },
            { slot: 0, teams: ['D'], field: 5 },
            { slot: 1, teams: ['E', 'I'], field: 0 },
            { slot: 1, teams: ['J', 'H'], field: 1 },
            { slot: 1, teams: ['F', 'D'], field: 2 },
            { slot: 1, teams: ['A', 'K'], field: 3 },
            { slot: 1, teams: ['C', 'G'], field: 4 },
            { slot: 1, teams: ['B'], field: 5 },
            { slot: 2, teams: ['K', 'B'], field: 0 },
            { slot: 2, teams: ['F', 'G'], field: 1 },
            { slot: 2, teams: ['E', 'J'], field: 2 },
            { slot: 2, teams: ['D', 'I'], field: 3 },
            { slot: 2, teams: ['C', 'H'], field: 4 },
            { slot: 2, teams: ['A'], field: 5 },
            { slot: 3, teams: ['F', 'K'], field: 0 },
            { slot: 3, teams: ['B', 'I'], field: 1 },
            { slot: 3, teams: ['D', 'G'], field: 2 },
            { slot: 3, teams: ['E', 'H'], field: 3 },
            { slot: 3, teams: ['A', 'J'], field: 4 },
            { slot: 3, teams: ['C'], field: 5 },
            { slot: 4, teams: ['E', 'B'], field: 0 },
            { slot: 4, teams: ['D', 'A'], field: 1 },
            { slot: 4, teams: ['F', 'C'], field: 2 },
            { slot: 4, teams: ['G', 'K'], field: 3 },
            { slot: 4, teams: ['I', 'H'], field: 4 },
            { slot: 4, teams: ['J'], field: 5 },
            { slot: 5, teams: ['A', 'G'], field: 0 },
            { slot: 5, teams: ['I', 'K'], field: 1 },
            { slot: 5, teams: ['B', 'H'], field: 2 },
            { slot: 5, teams: ['C', 'F'], field: 3 },
            { slot: 5, teams: ['D', 'J'], field: 4 },
            { slot: 5, teams: ['E'], field: 5 },
            { slot: 6, teams: ['B', 'D'], field: 0 },
            { slot: 6, teams: ['G', 'J'], field: 1 },
            { slot: 6, teams: ['A', 'C'], field: 2 },
            { slot: 6, teams: ['E', 'F'], field: 3 },
            { slot: 6, teams: ['I', 'K'], field: 4 },
            { slot: 6, teams: ['H'], field: 5 },
        ]
    },
    {
        category: 'F',
        teams: [ 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'J' ],
        players: { min: 4, max: 7 },
        fields: [
            { name: '1', format: '4 v 4', players: 4, duration: 720 },
            { name: '2', format: '3 v 3', players: 3, duration: 720 },
            { name: '3', format: '4 v 4', players: 4, duration: 720 },
            { name: '4', format: '3 v 3', players: 3, duration: 720 },
            { name: '5', format: '4 v 4', players: 4, duration: 720 },
            { name: '6', format: '3 v 3', players: 4, duration: 720 }
        ],
        matches: [
            { slot: 0, teams: ['C', 'F'], field: 0 },
            { slot: 0, teams: ['E', 'H'], field: 1 },
            { slot: 0, teams: ['L', 'K'], field: 2 },
            { slot: 0, teams: ['B', 'I'], field: 3 },
            { slot: 0, teams: ['D', 'G'], field: 4 },
            { slot: 0, teams: ['A', 'J'], field: 5 },
            { slot: 1, teams: ['E', 'I'], field: 0 },
            { slot: 1, teams: ['A', 'K'], field: 1 },
            { slot: 1, teams: ['B', 'L'], field: 2 },
            { slot: 1, teams: ['D', 'H'], field: 3 },
            { slot: 1, teams: ['F', 'J'], field: 4 },
            { slot: 1, teams: ['C', 'G'], field: 5 },
            { slot: 2, teams: ['A', 'G'], field: 0 },
            { slot: 2, teams: ['C', 'L'], field: 1 },
            { slot: 2, teams: ['D', 'J'], field: 2 },
            { slot: 2, teams: ['F', 'I'], field: 3 },
            { slot: 2, teams: ['B', 'H'], field: 4 },
            { slot: 2, teams: ['E', 'K'], field: 5 },
            { slot: 3, teams: ['F', 'H'], field: 0 },
            { slot: 3, teams: ['B', 'J'], field: 1 },
            { slot: 3, teams: ['C', 'K'], field: 2 },
            { slot: 3, teams: ['E', 'G'], field: 3 },
            { slot: 3, teams: ['A', 'I'], field: 4 },
            { slot: 3, teams: ['D', 'L'], field: 5 },
            { slot: 4, teams: ['K', 'G'], field: 0 },
            { slot: 4, teams: ['D', 'I'], field: 1 },
            { slot: 4, teams: ['E', 'J'], field: 2 },
            { slot: 4, teams: ['A', 'L'], field: 3 },
            { slot: 4, teams: ['C', 'H'], field: 4 },
            { slot: 4, teams: ['F', 'B'], field: 5 },
            { slot: 5, teams: ['A', 'D'], field: 0 },
            { slot: 5, teams: ['G', 'F'], field: 1 },
            { slot: 5, teams: ['I', 'L'], field: 2 },
            { slot: 5, teams: ['C', 'J'], field: 3 },
            { slot: 5, teams: ['B', 'E'], field: 4 },
            { slot: 5, teams: ['H', 'K'], field: 5 },
            { slot: 6, teams: ['A', 'B'], field: 0 },
            { slot: 6, teams: ['G', 'H'], field: 1 },
            { slot: 6, teams: ['C', 'D'], field: 2 },
            { slot: 6, teams: ['I', 'K'], field: 3 },
            { slot: 6, teams: ['E', 'F'], field: 4 },
            { slot: 6, teams: ['J', 'L'], field: 5 }
        ]
    }
]

export const useTournamentStore = defineStore({
    id: 'tournament',
    state: () => ({
        team: 'A',
        active: null
    }),
    getters: {
        allTournaments() {
            return tournaments.map(t => ({ ...t, title: t.category + ' / ' + t.teams.length + " Teams" }))
        }
    },
    actions: {
        startTournament(tournament, team, players) {
            this.active = {
                team,
                players,
                category: tournament.category,
                nextMatch: 0,
                matches: tournament.matches.filter(m => m.teams.includes(team)).map(m => ({
                    duration: tournament.fields[m.field].duration,
                    teams: m.teams,
                    field: tournament.fields[m.field].name,
                    format: {
                        name: tournament.fields[m.field].format,
                        players: tournament.fields[m.field].players
                    }
                })),
                nextMatch: 0
            };
        },
        nextMatch() {
            this.active.nextMatch++
        }
    }
})